### PR TITLE
* #4: Unified error handling using `com.exasol:error-reporting-java`.

### LINKED ISSUE #4: Unify exceptions handling
## Problem

We need to add our new exception builder to the project and unify the exceptions handling

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #4

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/teradata/TeradataColumnMetadataReader.java [hunk 1]
```diff
@@ -78,8 +79,13 @@ private DataType getOtherDataType(final JdbcTypeDescription jdbcTypeDescription)
                         + " This happens when the view the columns belong to is invalid. Ignoring columns.");
                 return Collections.emptyList();
             } else {
-                throw new RemoteMetadataReaderException("Unable to read column metadata from remote for catalog \""
-                        + catalogName + "\" and schema \"" + schemaName + "\"", exception);
+                throw new RemoteMetadataReaderException(ExaError.messageBuilder("VS-TD-2") //
+                        .message("Unable to read column metadata from remote for catalog {{catalogName}} " //
+                                + "and schema {{schemaName}}. Caused by: {{cause}}")
```
Comment (jakobbraun) [inline src/main/java/com/exasol/adapter/dialects/teradata/TeradataColumnMetadataReader.java:84]: I think we no longer need the `Caused by:` since stack traces work now?

**Review by jakobbraun — APPROVED** [review]
approved wirh comment

**Comment by jakobbraun** [comment]
Con't forget to mention the isue with Closes

File: src/main/java/com/exasol/adapter/dialects/teradata/TeradataColumnMetadataReader.java (hunk 1 above)
Comment (AnastasiiaSergienko) [reply src/main/java/com/exasol/adapter/dialects/teradata/TeradataColumnMetadataReader.java:84]: But for the previous Exasol versions it's still the only way to see the trace And not all users immediately migrated to Exasol 7  I guess
